### ISSUE TITLE
The last command in the docker file shouldn't be the rails server

### ISSUE THREAD

**Issue by cwant** [ualbertalib/di_docker_hydranorth#5]
Hi Alex,

Looking at this line:

https://github.com/ualbertalib/DIDocker_HydraNorth/blob/master/files/start_mysql.sh#L32

I think you should have something else at the end of the file to keep the container alive. I am finding that I want to restart the rails server occasionally, but doing so kills the entire container.

Cheers,
Chris

**Comment by alexstrilets** [comment]
can do something like tail -f logile

**Comment by weiweishi** [comment]
Addressed by https://github.com/ualbertalib/di_docker_hydranorth/blob/master/runDockerImage.sh#L23 in PR #10.
