### ISSUE TITLE
ClamAV: is it necessary?

### ISSUE THREAD

**Issue by cwant** [ualbertalib/di_docker_hydranorth#6]
Hi Alex,

Looks like ClamAV is installed:

https://github.com/ualbertalib/DIDocker_HydraNorth/blob/master/Dockerfile.mysql#L11

Is it necessary? It basically adds the following output to almost every command issued in the container:

```
LibClamAV Warning: **************************************************
LibClamAV Warning: ***  The virus database is older than 7 days!  ***
LibClamAV Warning: ***   Please update it as soon as possible.    ***
LibClamAV Warning: **************************************************

```
If ClamAV is necessary, perhaps there can be a task that updates it's database so that we don't see this message all the time.

Cheers,
Chris

**Comment by alexstrilets** [comment]
yes, we need clamAV we do scan items before injesting

**Comment by cwant** [comment]
Sounds good, closing the ticket (and thanks for the tip about running "freshclam" during our conversation about this).
