### ISSUE TITLE
Zip needed for item migration

### ISSUE THREAD

**Issue by cwant** [ualbertalib/di_docker_hydranorth#7]
Zip needs to be installed in the container for this migration to run successfully:

rake migration:eraitem['lib/tasks/migration/test-metadata']

See: https://github.com/ualbertalib/HydraNorth#batch-ingest

**Comment by alexstrilets** [comment]
installed.

**Comment by mbarnett** [comment]
Where is this installed? I don't see an Pull Request related to this. You didn't push whatever you did to this repo, which is really bad practice
